#!/bin/bash

#
# Generated by Webintrinsics Clusterlite:
# __COMMAND__
#
# Parameters: __PARSED_ARGUMENTS__
# Environment: __ENVIRONMENT__
# Prerequisites:
# - clusterlite install
#

set -e

install_services() {
__INSTALL_SERVICES_PART__
}

run() {
    install_services
    echo "__LOG__ done"
}
run