#!/bin/bash

#
# Generated by Webintrinsics Clusterlite:
# __COMMAND__
#
# Parameters: __PARSED_ARGUMENTS__
# Environment: __ENVIRONMENT__
# Prerequisites:
# - clusterlite install
#

set -e

apply() {
__INSTALL_SERVICES_PART__

    echo "__LOG__ done"
}
apply
