#!/bin/bash

#
# Generated by Webintrinsics Clusterlite:
# __COMMAND__
#
# Parameters: __PARSED_ARGUMENTS__
#
# Prerequisites:
# - Docker engine
# - Internet connection
#

set -e

echo "__LOG__ clusterlite node is already installed, no actions required"

echo "__LOG__ done"

