#!/bin/bash

#
# Generated by Webintrinsics Clusterlite:
# __COMMAND__
#
# Parameters: __PARSED_ARGUMENTS__
#
# Prerequisites:
# - clusterlite install
#

set -e

(>&2 echo "__LOG__ clusterlite node is not installed, no actions required")

(>&2 echo "__LOG__ done")

