#!/bin/bash

#
# Generated by Webintrinsics Clusterlite:
# __COMMAND__
#
# Parameters: __PARSED_ARGUMENTS__
#
# Prerequisites:
# - clusterlite install
#

set -e

uninstall_volume() {
    echo "__LOG__ uninstalling data directory"
    rm /var/lib/clusterlite/volume.txt || echo "__LOG__ warning: some data has not been removed"
    rm -Rf /var/lib/clusterlite || echo "__LOG__ warning: some data has not been removed"
    rm -Rf __VOLUME__ || echo "__LOG__ warning: some data has not been removed"
}

uninstall_weave() {
    echo "__LOG__ uninstalling weave network"
    weave reset
}

uninstall_weave
uninstall_volume

# TODO think about dropping loaded images and finished containers

echo "__LOG__ done"

